server:
  port: 8091
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:root@eureka:7001/eureka
  instance:
    instance-id: software-springcloud-product
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
spring:
  application:
    name: software-springcloud-product

